# Generated by Django 5.0.3 on 2024-03-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("veg_or_nonveg", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="menu_images/")),
                ("is_available", models.BooleanField()),
                (
                    "category",
                    models.ManyToManyField(related_name="item", to="home.category"),
                ),
            ],
        ),
    ]
