# Generated by Django 5.0.3 on 2024-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_category_slug_alter_menu_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="item", to="home.category"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="veg_or_nonveg",
            field=models.CharField(
                choices=[("veg", "Veg"), ("non_veg", "NonVeg")], max_length=10
            ),
        ),
    ]
