# Generated by Django 5.0.3 on 2024-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_menu_category_alter_menu_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="veg_or_nonveg",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="avg_time_taken",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="veg_nonveg_egg",
            field=models.CharField(
                choices=[
                    ("veg", "veg only"),
                    ("non_veg", "non-veg only"),
                    ("egg", "contains egg"),
                ],
                default="veg",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="item", to="home.category"
            ),
        ),
    ]
