# Generated by Django 5.0.3 on 2024-06-20 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
    ]
