# Generated by Django 5.0.3 on 2024-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="mode_of_eating",
            field=models.CharField(
                choices=[
                    ("take-away", "Take-away"),
                    ("dine-in", "Dine-in"),
                    ("delivery", "Delivery"),
                ],
                max_length=100,
            ),
        ),
    ]
