# Generated by Django 5.0.3 on 2024-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_address_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.TextField(),
        ),
    ]
