# Generated by Django 5.0.3 on 2024-06-26 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_menu_veg_or_nonveg_category_image_and_more"),
        ("orders", "0004_alter_address_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="items",
        ),
        migrations.AlterField(
            model_name="orders",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.menu"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.orders",
                    ),
                ),
            ],
        ),
    ]
